import type { Metadata } from "next";
import { ArrowRight, Check, Minus } from "lucide-react";
import { Magnetic } from "@/components/Magnetic";
import { Reveal, Stagger, StaggerItem } from "@/components/Reveal";
import { comparisonRows, packageFaqs, packages } from "@/data/packages";

export const metadata: Metadata = { title: "Packages", description: "Compare ClassPass packages for institutes at every stage of growth." };

export default function PackagesPage() {
  return (
    <>
      <section className="relative overflow-hidden bg-[#020b18] pb-28 pt-40 text-white">
        <div className="ink-grid absolute inset-0 opacity-60" /><div className="blue-orb absolute -left-32 top-20 size-[420px] rounded-full blur-[120px]" />
        <Reveal className="site-container relative grid gap-10 lg:grid-cols-[1fr_.6fr] lg:items-end"><div><span className="text-[10px] font-black uppercase tracking-[.2em] text-[#1D8AF4]">Packages built to scale</span><h1 className="mt-6 text-balance text-6xl font-black leading-[.9] tracking-[-.07em] sm:text-8xl">Start focused.<br /><span className="text-transparent bg-gradient-to-r from-[#0C55D0] to-[#1D8AF4] bg-clip-text">Scale clearly.</span></h1></div><p className="max-w-lg text-lg leading-8 text-white/50">Choose a capability level for today. Keep the operating foundation when your students, team and locations grow.</p></Reveal>
      </section>

      <section className="section-space bg-[#f4f8fc] text-[#031530]">
        <Stagger step={0.12} className="site-container grid gap-5 lg:grid-cols-3">
          {packages.map((plan, index) => <StaggerItem key={plan.name} variant="up" className="h-full"><article className={`shimmer-panel hover-lift relative flex h-full min-h-[600px] flex-col overflow-hidden rounded-[28px] border p-8 ${index === 0 ? "border-slate-200 bg-white text-[#031530] shadow-[0_20px_60px_rgba(3,21,48,.08)]" : index === 1 ? "border-blue-400/30 bg-gradient-to-b from-[#0C55D0] to-[#06377f] text-white shadow-[0_30px_80px_rgba(12,85,208,.25)]" : "border-white/10 bg-[#031530] text-white"}`}>
            <span className="text-[10px] font-black uppercase tracking-[.2em] text-[#1D8AF4]">{plan.audience}</span>{plan.featured && <span className="absolute right-6 top-6 rounded-full bg-white px-3 py-1.5 text-[8px] font-black uppercase tracking-[.14em] text-[#0C55D0]">Most popular</span>}
            <h2 className="mt-10 text-5xl font-black tracking-[-.06em]">{plan.name}</h2><p className={`mt-5 min-h-24 text-sm leading-7 ${index === 0 ? "text-slate-500" : "text-white/55"}`}>{plan.description}</p><div className={`my-7 h-px ${index === 0 ? "bg-slate-200" : "bg-white/15"}`} /><p className="text-[9px] font-black uppercase tracking-[.18em]">What&apos;s included</p><ul className="mt-6 flex-1 space-y-4">{plan.features.map((feature) => <li key={feature} className={`flex gap-3 text-sm ${index === 0 ? "text-slate-600" : "text-white/70"}`}><span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-[#1D8AF4]/20"><Check className={`size-3 ${index === 0 ? "text-[#0C55D0]" : "text-white"}`} /></span>{feature}</li>)}</ul><a href={`mailto:support@ams.com?subject=ClassPass%20${plan.name}%20package`} className={`group mt-8 flex items-center justify-between rounded-xl px-5 py-4 text-sm font-extrabold transition hover:-translate-y-0.5 ${index === 0 ? "bg-[#0C55D0] text-white" : "bg-white text-[#031530]"}`}>Request pricing <ArrowRight className="size-4 transition group-hover:translate-x-1" /></a>
          </article></StaggerItem>)}
        </Stagger>
        <p className="site-container mt-6 text-center text-xs text-[#66727f]">Final pricing is tailored to student volume, locations, messaging and onboarding requirements.</p>
      </section>

      <section className="section-space bg-[#020b18] text-white">
        <div className="site-container"><div className="grid gap-6 lg:grid-cols-2 lg:items-end"><Reveal variant="left"><span className="text-[10px] font-black uppercase tracking-[.2em] text-[#1D8AF4]">Full comparison</span><h2 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em]">No hidden capability gaps.</h2></Reveal><Reveal variant="right" delay={0.1}><p className="max-w-lg text-sm leading-7 text-white/45 lg:ml-auto">Scroll horizontally on smaller screens to compare every package.</p></Reveal></div>
          <Reveal delay={0.1} className="mt-12 overflow-hidden rounded-[24px] bg-[#031530] shadow-[0_20px_60px_rgba(0,8,24,.3)] ring-1 ring-white/10"><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="bg-[#0C55D0] text-white"><th className="sticky left-0 z-10 min-w-64 bg-[#0C55D0] px-6 py-5 text-[10px] font-black uppercase tracking-[.16em] text-white/60">Capability</th>{packages.map((plan) => <th key={plan.name} className="min-w-40 px-6 py-5 text-lg font-black">{plan.name}</th>)}</tr></thead><tbody>{comparisonRows.map((row, index) => <tr key={row.capability} className="border-b border-white/10 last:border-0 hover:bg-[#1D8AF4]/10"><th className="sticky left-0 z-10 bg-[#031530] px-6 py-4 font-bold text-white">{index === 0 || comparisonRows[index - 1].category !== row.category ? <span className="mb-1 block text-[8px] font-black uppercase tracking-[.16em] text-[#1D8AF4]">{row.category}</span> : null}{row.capability}</th>{([row.launch, row.scale, row.network] as const).map((value, cell) => <td key={cell} className="px-6 py-4 text-white/60">{typeof value === "string" ? value : value ? <span className="flex size-6 items-center justify-center rounded-full bg-[#0C55D0]"><Check className="size-3 text-white" /></span> : <Minus className="size-4 text-white/20" />}</td>)}</tr>)}</tbody></table></div></Reveal>
        </div>
      </section>

      <section id="consultation" className="section-space bg-gradient-to-br from-[#031530] via-[#0C55D0] to-[#1D8AF4] text-white"><Reveal variant="scale" className="site-container grid gap-10 lg:grid-cols-[1fr_.65fr] lg:items-center"><div><span className="text-[10px] font-black uppercase tracking-[.2em] text-blue-200">A package shaped around you</span><h2 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em] sm:text-7xl">Let&apos;s map the right fit.</h2><p className="mt-6 max-w-xl leading-7 text-white/55">Tell us about your student count, locations and current process. We’ll recommend the right rollout.</p></div><Magnetic strength={0.2}><a href="mailto:support@ams.com?subject=ClassPass%20package%20consultation" className="group flex items-center justify-between rounded-2xl bg-[#020b18] p-6 text-lg font-black text-white transition hover:shadow-[0_25px_60px_rgba(2,11,24,.5)]">Start the conversation <ArrowRight className="size-5 transition group-hover:translate-x-1" /></a></Magnetic></Reveal></section>

      <section className="section-space bg-white text-[#031530]"><div className="site-container grid gap-12 lg:grid-cols-[.65fr_1fr]"><Reveal><span className="text-[10px] font-black uppercase tracking-[.2em] text-[#0C55D0]">Common questions</span><h2 className="mt-5 text-5xl font-black leading-[.95] tracking-[-.06em]">Useful answers, upfront.</h2></Reveal><Stagger step={0.09} className="space-y-3">{packageFaqs.map((faq) => <StaggerItem key={faq.question} variant="right"><details className="group rounded-2xl bg-[#f4f8fc] p-6 ring-1 ring-[#031530]/10 transition-shadow hover:shadow-[0_14px_40px_rgba(3,21,48,.08)]"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-black"><span>{faq.question}</span><span className="text-xl text-[#1D8AF4] transition group-open:rotate-45">+</span></summary><p className="mt-4 pr-6 text-sm leading-7 text-slate-600">{faq.answer}</p></details></StaggerItem>)}</Stagger></div></section>
    </>
  );
}
